// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : sigamani
Date           : Thu Jun 25 13:03:42 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.23.3.el6.x86_64 #1 SMP Wed Jul 30 09:43:11 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/s/sigamani/public/CMSSW_7_2_3-13TeV-DiLeptonStops/src/Stops-dilepton/BDT/TMVA-v4.2.0/test
Training events: 23770
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
LepPt                         LepPt                         LepPt                         LepPt                                                           'F'    [3.00557041168,29.9953708649]
LepEta                        LepEta                        LepEta                        LepEta                                                          'F'    [-2.49807977676,2.49768900871]
LepPhi                        LepPhi                        LepPhi                        LepPhi                                                          'F'    [-3.14147806168,3.14141702652]
Met                           Met                           Met                           Met                                                             'F'    [200.000610352,916.490722656]
MetPhi                        MetPhi                        MetPhi                        MetPhi                                                          'F'    [-3.14155578613,3.14143371582]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "LepPt", "LepEta", "LepPhi", "Met", "MetPhi" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 1.01158791454791;
   fWeightMatrix0to1[1][0] = 1.46400548308417;
   fWeightMatrix0to1[2][0] = 0.649628312772003;
   fWeightMatrix0to1[3][0] = 2.97797584752021;
   fWeightMatrix0to1[4][0] = -2.61129334414181;
   fWeightMatrix0to1[5][0] = -0.911136741864753;
   fWeightMatrix0to1[6][0] = -0.671663190051786;
   fWeightMatrix0to1[7][0] = 1.26325781490544;
   fWeightMatrix0to1[8][0] = -1.47141465767791;
   fWeightMatrix0to1[9][0] = -0.944051957981032;
   fWeightMatrix0to1[0][1] = -1.0814871564418;
   fWeightMatrix0to1[1][1] = -0.89403257350535;
   fWeightMatrix0to1[2][1] = -1.04667450375514;
   fWeightMatrix0to1[3][1] = -0.0360704435594593;
   fWeightMatrix0to1[4][1] = -0.27054972236928;
   fWeightMatrix0to1[5][1] = 0.660318604224659;
   fWeightMatrix0to1[6][1] = -0.33763562322586;
   fWeightMatrix0to1[7][1] = 1.36423492090188;
   fWeightMatrix0to1[8][1] = -0.177589942668875;
   fWeightMatrix0to1[9][1] = 1.01359128387342;
   fWeightMatrix0to1[0][2] = -0.0863093960601835;
   fWeightMatrix0to1[1][2] = -0.251696430507972;
   fWeightMatrix0to1[2][2] = 0.608352805043057;
   fWeightMatrix0to1[3][2] = -0.00699689303558594;
   fWeightMatrix0to1[4][2] = 0.0450977204530554;
   fWeightMatrix0to1[5][2] = -0.404332435369458;
   fWeightMatrix0to1[6][2] = 1.05204987820905;
   fWeightMatrix0to1[7][2] = -0.371107164232492;
   fWeightMatrix0to1[8][2] = -1.94611212988186;
   fWeightMatrix0to1[9][2] = -0.303718015260641;
   fWeightMatrix0to1[0][3] = -0.115289160494344;
   fWeightMatrix0to1[1][3] = 1.02631024640327;
   fWeightMatrix0to1[2][3] = -1.17069661539711;
   fWeightMatrix0to1[3][3] = -0.353621316890855;
   fWeightMatrix0to1[4][3] = 0.89900781593372;
   fWeightMatrix0to1[5][3] = -0.0429090511896224;
   fWeightMatrix0to1[6][3] = -0.979711751577274;
   fWeightMatrix0to1[7][3] = 1.76619144124545;
   fWeightMatrix0to1[8][3] = -0.589580943266006;
   fWeightMatrix0to1[9][3] = 2.2096681969508;
   fWeightMatrix0to1[0][4] = 0.115841398293147;
   fWeightMatrix0to1[1][4] = 0.0930193209310786;
   fWeightMatrix0to1[2][4] = 1.79064446748772;
   fWeightMatrix0to1[3][4] = -0.0487659114640448;
   fWeightMatrix0to1[4][4] = 0.037034902587973;
   fWeightMatrix0to1[5][4] = -1.07465140609015;
   fWeightMatrix0to1[6][4] = 0.470001459821412;
   fWeightMatrix0to1[7][4] = 0.0903833938613585;
   fWeightMatrix0to1[8][4] = 1.55425690569505;
   fWeightMatrix0to1[9][4] = 0.144175591512988;
   fWeightMatrix0to1[0][5] = 1.88889705677436;
   fWeightMatrix0to1[1][5] = 1.69535342021225;
   fWeightMatrix0to1[2][5] = -0.762998663827484;
   fWeightMatrix0to1[3][5] = 3.23869769933841;
   fWeightMatrix0to1[4][5] = -1.74411010131012;
   fWeightMatrix0to1[5][5] = -1.42064035291609;
   fWeightMatrix0to1[6][5] = -1.6523124195872;
   fWeightMatrix0to1[7][5] = -2.8531482070445;
   fWeightMatrix0to1[8][5] = 1.0597451898288;
   fWeightMatrix0to1[9][5] = -0.462175170679139;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.266394438592462;
   fWeightMatrix1to2[0][1] = 0.0510684956897705;
   fWeightMatrix1to2[0][2] = -0.0015623900175509;
   fWeightMatrix1to2[0][3] = 1.17888300899698;
   fWeightMatrix1to2[0][4] = 0.460298478270646;
   fWeightMatrix1to2[0][5] = -0.0156072631761734;
   fWeightMatrix1to2[0][6] = -0.00278193695743161;
   fWeightMatrix1to2[0][7] = -0.185120791187923;
   fWeightMatrix1to2[0][8] = -0.00109620223580285;
   fWeightMatrix1to2[0][9] = 0.136778283689067;
   fWeightMatrix1to2[0][10] = -0.562275302046003;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5.00175189972;
   fMax_1[0][0] = 29.3404064178;
   fMin_1[1][0] = 3.00557041168;
   fMax_1[1][0] = 29.9953708649;
   fMin_1[2][0] = 3.00557041168;
   fMax_1[2][0] = 29.9953708649;
   fMin_1[0][1] = -2.46032905579;
   fMax_1[0][1] = 2.46690416336;
   fMin_1[1][1] = -2.49807977676;
   fMax_1[1][1] = 2.49768900871;
   fMin_1[2][1] = -2.49807977676;
   fMax_1[2][1] = 2.49768900871;
   fMin_1[0][2] = -3.10826039314;
   fMax_1[0][2] = 3.11266422272;
   fMin_1[1][2] = -3.14147806168;
   fMax_1[1][2] = 3.14141702652;
   fMin_1[2][2] = -3.14147806168;
   fMax_1[2][2] = 3.14141702652;
   fMin_1[0][3] = 200.051651001;
   fMax_1[0][3] = 845.63079834;
   fMin_1[1][3] = 200.000610352;
   fMax_1[1][3] = 916.490722656;
   fMin_1[2][3] = 200.000610352;
   fMax_1[2][3] = 916.490722656;
   fMin_1[0][4] = -3.13187551498;
   fMax_1[0][4] = 3.12969923019;
   fMin_1[1][4] = -3.14155578613;
   fMax_1[1][4] = 3.14143371582;
   fMin_1[2][4] = -3.14155578613;
   fMax_1[2][4] = 3.14143371582;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
